### ISSUE TITLE
Could  you  please provide the imglist_80k.txt ?

### ISSUE THREAD

**Issue by Albert-Ye** [yxu0611/Tensorflow-implementation-of-LCNN#1]
Could  you  please provide the imglist_80k.txt ?

**Comment by yxu0611** [comment]
Thank you for your interest. Please go to this link to access the imglist_70K of MS-Celeb-1M cleaned data: https://1drv.ms/t/s!AleP5K29t5x7gfEu_3My1D3lgDhLlQ

**Comment by Albert-Ye** [comment]
Thank you very much! Could you please provide the imglist_10k.txt ?

**Comment by yxu0611** [comment]
For the imglist_10k.txt, you can simply select the top 10k identities from imglist_70k. Here I also share my imglist_10k.txt: https://1drv.ms/t/s!AleP5K29t5x7ge87YS8Ue92h8JDDMw
